"""The HTTP tier of the Brain SDK — :class:`BrainHttpClient` + contract types.

Talks JSON to the Brain HTTP edge (``brain-edge`` self-hosted, or the Arc cloud
gateway). The native wire client is :class:`brain_db_sdk.BrainClient`.
"""

from __future__ import annotations

from .client import DEFAULT_BASE_URL, BrainHttpClient
from .errors import BrainHttpError
from .retry import HttpRetryPolicy
from .types import (
    Capabilities,
    CreateEntityResult,
    EncodeResult,
    EntityDetail,
    ForgetResult,
    GraphEdge,
    GraphNode,
    GraphPage,
    InferenceStep,
    LinkResult,
    ListEntitiesResult,
    ListRelationsResult,
    ListStatementsResult,
    MemoryHit,
    MemoryInspect,
    MemoryListItem,
    MemoryListPage,
    Permissions,
    PlanResult,
    PlanStep,
    ReasonResult,
    RecallResult,
    RelationDetail,
    ResolveEntityResult,
    Schema,
    SchemaError,
    SchemaReplace,
    SchemaUpload,
    SchemaValidate,
    StageArtifact,
    StageGraph,
    StageGraphEdge,
    StageGraphNode,
    StageKeywordField,
    StageRecord,
    StatementDetail,
    StatementObject,
    StatementValue,
    TraversalPath,
    TraversalStep,
    TraverseResult,
    UnlinkResult,
    Whoami,
)

__all__ = [
    "BrainHttpClient",
    "BrainHttpError",
    "HttpRetryPolicy",
    "DEFAULT_BASE_URL",
    "Capabilities",
    "CreateEntityResult",
    "EncodeResult",
    "EntityDetail",
    "ForgetResult",
    "GraphEdge",
    "GraphNode",
    "GraphPage",
    "InferenceStep",
    "LinkResult",
    "ListEntitiesResult",
    "ListRelationsResult",
    "ListStatementsResult",
    "MemoryHit",
    "MemoryInspect",
    "MemoryListItem",
    "MemoryListPage",
    "Permissions",
    "PlanResult",
    "PlanStep",
    "ReasonResult",
    "RecallResult",
    "RelationDetail",
    "ResolveEntityResult",
    "Schema",
    "SchemaError",
    "SchemaReplace",
    "SchemaUpload",
    "SchemaValidate",
    "StageArtifact",
    "StageGraph",
    "StageGraphEdge",
    "StageGraphNode",
    "StageKeywordField",
    "StageRecord",
    "StatementDetail",
    "StatementObject",
    "StatementValue",
    "TraversalPath",
    "TraversalStep",
    "TraverseResult",
    "UnlinkResult",
    "Whoami",
]
